title: Open Game Icons
url: https://open-game-icons.net

markdown: kramdown

plugins:
  - jekyll_sqlite

collections:
  icon_pages:
    output: true
  tag_pages:
    output: true

sqlite:
  - collection: icon_pages
    file: assets/icons/icons.db
    query: |
      SELECT
        i.author AS path,
        i.id     AS name,
        '/1x1/' || i.author || '/' || i.id || '.html' AS permalink,
        i.author,
        i.id     AS icon_id,
        i.name   AS title,
        i.name   AS display_name,
        a.name   AS author_name,
        a.link   AS author_link,
        l.name   AS license_name,
        l.link   AS license_link,
        group_concat(DISTINCT it.tag) AS tags,
        'icon'   AS layout
      FROM icons i
      JOIN authors  a ON i.author  = a.id
      JOIN licenses l ON i.license = l.id
      LEFT JOIN icon_tags it ON i.author = it.author AND i.id = it.id
      GROUP BY i.author, i.id
      ORDER BY i.name, i.id

  - collection: tag_pages
    file: assets/icons/icons.db
    query: |
      SELECT
        t.id       AS name,
        '/tags/' || t.id || '.html' AS permalink,
        t.id       AS slug,
        t.name     AS title,
        t.name     AS list_name,
        'tag_page' AS layout
      FROM tags t
      JOIN icon_tags it ON t.id = it.tag
      GROUP BY t.id
      HAVING count(*) > 1

  - data: tag_info_array
    file: assets/icons/icons.db
    query: |
      SELECT
      	t.id,
        t.name,
        t.parent,
        count(it.tag) AS count
      FROM tags t
      LEFT JOIN icon_tags it ON t.id = it.tag
      GROUP BY t.id

  - data: tag_icons_array
    file: assets/icons/icons.db
    query: |
      SELECT
      	it.tag,
        i.author,
        i.id,
        i.id AS icon_id,
        i.name,
        i.name AS title
      FROM icon_tags it
      JOIN icons i ON it.author = i.author AND it.id = i.id
      ORDER BY i.name, i.id

  - data: search_index_array
    file: assets/icons/icons.db
    query: |
      SELECT
      	i.author,
        i.id,
        i.name,
        group_concat(DISTINCT it.tag)     AS tag_list,
        group_concat(DISTINCT ik.keyword) AS keyword_list
      FROM icons i
      LEFT JOIN icon_tags     it ON i.author = it.author AND i.id = it.id
      LEFT JOIN icon_keywords ik ON i.author = ik.author AND i.id = ik.id
      GROUP BY i.author, i.id

exclude:
  - AGENTS.md
  - README.md
  - .zed
  - .gitignore
